import { createContext, useContext, useState } from 'react'

const translations = {
  en: {
    lang: 'EN',
    nav: {
      home: 'Home', experience: 'The Experience', gaming: 'YA Gaming',
      social: 'YA Social', collectibles: 'Collectibles / TCG', tcg: 'TCG Lounge',
      bundles: 'Bundles & Passes', howto: 'How to Play', stores: 'Stores',
      events: 'Events', club: 'YAMATO Club', contact: 'Contact', shop: 'Shop',
      prizes: 'Prizes',
    },
    hero: {
      badge: 'Now Open in Athens & Nea Erythraia',
      h1a: 'Where Reality', h1b: 'Becomes', h1c: 'Playable.',
      sub: "Not a store. Not a game room. Something entirely new.",
      tagline: 'Μπες στο παιχνίδι.',
      cta1: 'Explore the Experience', cta2: 'Find a Store',
    },
    stats: { machines: 'Arcade Machines', zones: 'Game Zones', locations: 'Locations', fun: 'Hours of Fun' },
    footer: {
      desc: "Not a store. Not a game room. First in Greece. Built to redefine urban entertainment.",
      nav: 'Navigate', more: 'More', rights: '© 2026 YAMATO Urban Play. All rights reserved.',
      legal: 'Privacy Policy · Terms of Use · GDPR',
    },
    cta: { findStore: 'Find a Store', joinClub: 'Join the Club', viewAll: 'View All', browseAll: 'Browse All' },
    home: {
      featuredGames: { sub: 'Step Inside', title: 'The Lineup.', mobileCta: 'View All Games' },
      categories: { sub: 'Explore', title: 'Game Categories' },
      prizeDrops: {
        sub: 'Current Lineup',
        cta: 'View All Drops',
        locationNote: 'Prize lineup may vary by location',
        dropBadge: 'Drop',
        scrollHint: 'scroll to explore',
      },
      prizeTeaser: {
        sub: "Win Something Real.",
        title: 'Prize games',
        titleAccent: 'worth playing for.',
        desc: "Claw machines, figure battles, skill challenges — loaded with anime heroes, gaming icons and pop-culture collectibles. Every play is a shot at something you'll actually want to keep.",
        cta1: 'Explore Prize Games',
        cta2: 'View Prize Drops',
        steps: [
          { n: '01', title: 'Choose', desc: 'Pick your machine and challenge.' },
          { n: '02', title: 'Aim',    desc: 'Skill and timing decide the win.' },
          { n: '03', title: 'Win',    desc: 'Claim your collectible.' },
          { n: '04', title: 'Display',desc: 'Your collection just got serious.' },
        ],
      },
      pillars: {
        sub: 'One rechargeable card.',
        title: 'The YAMATO Experience.',
        items: [
          { title: 'YA Gaming',      desc: '100+ premium arcade machines across 10 categories — from VR to classic pinball.' },
          { title: 'YA Social',      desc: 'AR darts, The Arena, shuffleboard — experiences built for groups and shared moments.' },
          { title: 'YA Collectibles',desc: 'TCG cards, limited merch, vinyl figures, and exclusive YAMATO drops.' },
          { title: 'TCG Lounge',     desc: "Pokémon, Yu-Gi-Oh!, One Piece tournaments and a dedicated community space." },
        ],
      },
      events: { sub: "What's On", title: 'Upcoming Events', cta: 'All Events' },
      bundles: {
        sub: 'One Card.',
        title: 'The YAMATO Experience.',
        desc: 'Load up and play — no entry fee, no limits. The YAMATO Playcard unlocks everything.',
        cta: 'View Passes',
      },
      faq: { sub: 'Questions', title: 'FAQ', cta: 'How to Play + Full FAQ' },
      club: {
        sub: 'Exclusive',
        title: 'Join the YAMATO Club',
        desc: 'Early access. Exclusive drops. Member-only events. For those who expect more than ordinary entertainment — and keep coming back.',
        cta: 'Pre-Register Now',
      },
    },
    ui: {
      perPage: 'Per page:',
      pageOf: 'page',
      of: 'of',
      loading: 'Loading…',
      loadingPrizes: 'Loading Prize Drops…',
      errorPrizes: 'Could not load prize drops.',
      explorePrizes: 'Explore Prize Games',
      prize: 'prize',
      prizes: 'prizes',
      products: 'products',
      scrollHint: 'scroll to explore',
      prevPage: '← Prev',
      nextPage: 'Next →',
      howToWin: 'How to Win',
      winSteps: [
        { n: '01', title: 'Choose your game',  desc: 'Pick a claw machine, figure game or skill challenge.' },
        { n: '02', title: 'Aim & time it',     desc: 'Test your skill, refine your technique.' },
        { n: '03', title: 'Win your prize',    desc: 'Take home a pop-culture collectible you actually want.' },
        { n: '04', title: 'Display & share',   desc: 'Show it off. Your collection just got serious.' },
      ],
      filters: 'Filters',
      search: 'Search…',
      all: 'All',
      categories: 'Categories',
      clearFilters: 'Clear Filters',
      noProducts: 'No products found',
      loadingProducts: 'Loading…',
    },
    pages: {
      experience: {
        hero: { sub: 'The Experience', title: 'Reality Becomes Playable.', desc: "Greece's first premium indoor amusement destination. Arcade, VR, social gaming, pop culture & collectibles — under one YAMATO roof." },
        philosophy: { label: 'Our Philosophy', title: 'Premium. Cinematic. Yours.', p1: 'YAMATO was born from a single idea: that play deserves to be premium. We curated the finest arcade experiences — VR, motion simulators, social AR, classic pinball, TCG — and brought them together in one dark, immersive space.', p2: 'The aesthetic is Japanese-inspired, urban, and raw. The experience is cinematic. The community is everything.', ctaBrowse: 'Browse Games', ctaFind: 'Find Us' },
        stats: [{ n:'100+', l:'Premium Machines' }, { n:'10', l:'Game Categories' }, { n:'VR', l:'Full Immersion' }, { n:'TCG', l:'Card Gaming Lounge' }],
        zones: { label: 'The Zones', title: 'Game Categories' },
        diff: { label: 'Why YAMATO', title: 'What Sets Us Apart' },
        diffItems: [
          { title: 'Curated, Not Random', desc: 'Every machine at YAMATO was hand-selected for quality, playability, and spectacle. No filler.' },
          { title: 'Premium Atmosphere', desc: 'Dark, cinematic, Japanese-inspired. A space that feels as good as the games that fill it.' },
          { title: 'Community First', desc: 'TCG tournaments, VR championships, retro nights. YAMATO is a destination, not just a venue.' },
        ],
      },
      gaming: {
        hero: { sub: 'YA Gaming', title: 'The Game Floor', desc: '100+ premium arcade machines across 10 categories. From cutting-edge VR to timeless classics.' },
        search: 'Search games…', all: 'All', noResults: 'No games found.',
      },
      social: {
        hero: { sub: 'YA Social', title: 'Play Together.', desc: 'Augmented reality, group arenas, darts, shuffleboard — experiences designed for shared moments and unforgettable nights out.' },
        section: { label: 'Social Gaming', title: 'Bring the whole Gang!', p1: "YAMATO's Social Entertainment & AR zone is where the magic happens for groups. Compete against friends in The Arena, challenge each other at AR Darts, or gather around the shuffleboard.", p2: 'Perfect for birthdays, corporate events, nights out, or just hanging with your crew.' },
        gamesLabel: 'Social Entertainment & AR', gamesTitle: 'All Social Experiences',
      },
      collectibles: {
        hero: { sub: 'YA Collectibles', title: 'Collect. Trade. Own.', desc: 'TCG cards, limited-edition merch, exclusive collaborations, and designer vinyl. The YAMATO store.' },
        inStore: 'Available in store', registerInterest: 'Register Interest',
        tcgSection: { label: 'TCG Lounge', title: 'Play, Trade & Compete', desc: 'Dedicated TCG space with regular tournaments and community events.', cta: 'Discover TCG Lounge' },
      },
      tcg: {
        hero: { sub: 'TCG Lounge', title: 'The Card Game Corner.', desc: 'A dedicated space for Trading Card Game players. Play, trade, collect, compete. Pokémon, Yu-Gi-Oh!, One Piece and more.' },
        games: [
          { name: 'Pokémon TCG', desc: 'Booster boxes, singles, and competitive play. Regular expansions in stock.' },
          { name: 'Yu-Gi-Oh!', desc: 'Collector tins, booster packs, and tournament-legal decks.' },
          { name: 'One Piece TCG', desc: 'Starter decks and boosters from the fastest-growing TCG on the market.' },
        ],
        products: { label: 'In Stock', title: 'TCG Products' },
        inStore: 'Available in store',
        tournaments: { label: 'Compete', title: 'Tournaments & Events', desc: 'We host regular TCG tournaments for all skill levels. Prizes, glory, and community await. Check our events page for upcoming dates.', cta1: 'See Events', cta2: 'Register Interest' },
        stats: [['Weekly','Local tournaments'],['All Levels','Beginner to Pro'],['Prizes','Win exclusive cards'],['Community','Grow your skills']],
      },
      bundles: {
        hero: { sub: 'Bundles & Passes', title: 'Play Your Way.', desc: 'YAMATO Playcard, Summer Pass, Whole Gang Pass, and Gift Cards. Available at all locations.' },
        custom: { title: 'Need something specific?', desc: 'Group bookings, corporate events, birthday packages — we\'ll tailor it for you.', cta: 'Contact Us' },
      },
      howto: {
        hero: { sub: 'How to Play', title: 'Get Into the Game.', desc: 'Everything you need to know to start your YAMATO journey.' },
        steps: { label: 'Step by Step', title: "It's Simple" },
        stepItems: [
          { n:'01', title:'Visit a YAMATO Location', desc:'Walk into any YAMATO store — Athens Center or Nea Erythraia. No booking required for individual play.' },
          { n:'02', title:'Get Your Playcard', desc:'Pick up a YAMATO Playcard at the front desk. Load it with credits — starting from €5.' },
          { n:'03', title:'Explore the Floor', desc:'Browse 100+ machines across 10 categories. Tap your Playcard on any machine to start playing.' },
          { n:'04', title:'Win, Level Up, Repeat', desc:'Collect tickets from redemption games, challenge friends, discover new experiences. The fun never stops.' },
        ],
        playcard: { label: 'Your Key to YAMATO', title: 'The YAMATO Playcard', p1: 'Reloadable, trackable, and works on every machine at every location. Load as little as €5 or stack up for a full session.', p2: 'Available at the front desk of all YAMATO locations.', cta: 'See Passes' },
        faq: { label: 'FAQ', title: 'Common Questions' },
      },
      stores: {
        hero: { sub: 'Locations', title: 'Find Your YAMATO.', desc: 'Two locations open in Attica. More coming soon across Greece.' },
        active: { label: 'Open Now', title: 'Active Locations' },
        mapExplore: 'Explore on Google Maps',
        coming: { label: 'Expansion', title: 'Coming Soon' },
        openInMaps: 'Open in Maps',
      },
      events: {
        hero: { sub: 'Events & Social Hub', title: "What's On.", desc: 'Tournaments, retro nights, family days, championships. The YAMATO event calendar.' },
        featured: { label: 'Featured', title: "Don't Miss" },
        upcoming: { label: 'Upcoming', title: 'All Events' },
        social: { label: 'Social', title: 'Follow the Action', desc: 'Stay updated on all events, drops, and community highlights.' },
      },
      club: {
        hero: { sub: 'YAMATO Club', title: 'Join the Inner Circle.', desc: 'Pre-register for the YAMATO Club. Exclusive benefits, early access, member drops and more. Launching with our first location.' },
        benefits: { label: 'Member Benefits', title: 'What You Get' },
        benefitItems: [
          { title: 'Early Access', desc: 'Get first access to new game launches, drops, and exclusive events before the general public.' },
          { title: 'Member Drops', desc: 'Exclusive YAMATO merchandise and limited-edition collectibles, reserved for members only.' },
          { title: 'Priority Events', desc: 'Guaranteed spots at TCG tournaments, VR championships, and member-only nights.' },
          { title: 'Member Perks', desc: 'Birthday bonuses, loyalty credits, and special rates on passes and bundles.' },
          { title: 'Community', desc: 'Join a private community of YAMATO players, collectors, and enthusiasts.' },
          { title: 'The Briefing', desc: 'Monthly YAMATO newsletter: new games, upcoming events, drops, and behind-the-scenes.' },
        ],
        form: { label: 'Pre-Registration', title: 'Claim Your Spot', sub: 'Free to join. No card required. GDPR compliant.' },
      },
      contact: {
        hero: { sub: 'Contact', title: 'Get in Touch.', desc: 'Questions, group bookings, press inquiries, or just want to say hi.' },
        form: { label: 'Send a Message', title: 'Contact Form' },
        locations: { label: 'Find Us', title: 'Locations' },
        openInMaps: 'Open in Maps',
        socialTitle: 'Social Media',
      },
      prizes: {
        hero: {
          title: 'Current Prize Drops.',
          desc: 'Anime heroes, gaming icons, cute characters and collectible figures you can win at YAMATO. No shopping cart. No online checkout. Just prizes worth playing for.',
          note: 'Available in selected YAMATO prize games. Prize lineup may vary.',
          cta1: 'Explore Prize Drops',
          cta2: 'How Prize Games Work',
        },
        featured: { label: '★ Featured Drops', title: 'Selected This Season' },
        filters: { all: 'All Prizes', hero: 'By Hero', brand: 'By Brand' },
        noResults: 'No prizes found.',
        gameTypeLabel: 'Win it in',
        playToWin: 'Play to Win',
        seeHowToWin: 'See How to Win',
        availableIn: 'Available in selected prize games',
        cta: {
          title: 'How do you win them?',
          desc: 'Choose a YAMATO prize game, test your skill, and take your favourite pop-culture hero home.',
          btn: 'Explore Prize Games',
        },
        homeTeaserTitle: 'Win the characters you actually want.',
        homeTeaserDesc: 'Anime heroes, gaming icons, cute characters and collectible figures waiting inside YAMATO prize games.',
        homeTeaserCta: 'View Prize Drops',
        prizeGamesTitle: 'Prize games worth playing for.',
        prizeGamesDesc: 'Skill-based machines, exciting challenges and premium pop-culture prizes waiting to be won.',
        prizeGamesCta: 'Explore Prize Games',
      },
    },
    auth: {
      signIn: 'Sign In',
      myYamato: 'My YAMATO',
      signInTitle: 'Sign in to YAMATO',
      signInDesc: "No password needed. Enter your email and we'll send you a secure sign-in link.",
      emailLabel: 'Email address',
      emailPlaceholder: 'your@email.com',
      sendOTP: 'Send sign-in link',
      sendLink: 'Send Sign-In Link',
      otpTitle: 'Check your email',
      otpDesc: 'We sent a 6-digit code to',
      otpLabel: 'Enter the 6-digit code',
      otpPlaceholder: '000000',
      verifyOTP: 'Verify code',
      backToEmail: 'Try a different email',
      sending: 'Sending…',
      verifying: 'Verifying…',
      signOut: 'Sign Out',
      checkEmail: 'Check Your Email',
      linkSentDesc: 'We sent a sign-in link to {email}. Click it to access your YAMATO account.',
      spamNote: "Can't find it? Check your spam folder.",
      tryAgain: 'Try a different email',
      rememberMe: 'Remember me for 30 days',
      noAccount: 'Not a member yet?',
      joinCTA: 'Join Club →',
    },
    join: {
      pageTitle: 'Join YAMATO Club',
      step1Title: 'Complete your profile',
      step1Desc: 'We use this to personalize your Club experience.',
      step2Title: 'What are you into?',
      step2Desc: 'Pick your favorites so we can show you more of what you love.',
      step3Title: 'Stay in the loop',
      step3Desc: 'Choose how you want to hear from YAMATO. You can update your preferences anytime.',
      welcomeTitle: 'Welcome to YAMATO Club',
      welcomeDesc: "You're in. Prize drops, member updates and YAMATO experiences are now closer than ever.",
      exploreCTA: 'Explore Prize Drops',
      dashboardCTA: 'Go to My YAMATO',
      alreadyMember: "You're already a YAMATO Club member!",
      firstName: 'First name',
      lastName: 'Last name',
      phone: 'Mobile phone',
      birthdate: 'Date of birth',
      agreeTerms: 'I accept the YAMATO Club Terms and Privacy Policy.',
      agreeEmail: 'I want to receive YAMATO news, offers and prize drop updates by email.',
      agreeSMS: 'I want to receive YAMATO news, offers and prize drop updates by SMS/Viber.',
      next: 'Continue',
      saving: 'Saving…',
      termsRequired: 'You must accept the Terms and Privacy Policy to join.',
      interests: ['Anime Heroes', 'Gaming Icons', 'Movies & Series', 'Cute & Kawaii', 'Collector Figures', 'Prize Drops', 'Special Offers', 'Events'],
    },
    dashboard: {
      title: 'My YAMATO',
      profile: 'My Profile',
      club: 'YAMATO Club',
      preferences: 'My Preferences',
      orders: 'My Orders',
      addresses: 'My Addresses',
      marketing: 'Marketing Preferences',
      signOut: 'Sign Out',
      memberSince: 'Member since',
      memberStatus: 'Membership',
      memberNumber: 'Member #',
      active: 'Active',
      pending: 'Pending',
      noOrders: 'No orders yet.',
      noAddresses: 'No addresses saved yet.',
      save: 'Save changes',
      saving: 'Saving…',
      saved: 'Saved!',
      addAddress: 'Add new address',
      defaultAddress: 'Default',
      setDefault: 'Set as default',
      deleteAddress: 'Delete',
      shipping: 'Shipping',
      billing: 'Billing',
      notMember: "You haven't joined YAMATO Club yet.",
      joinNow: 'Join YAMATO Club',
      firstName: 'First name',
      lastName: 'Last name',
      email: 'Email',
      phone: 'Mobile phone',
      birthdate: 'Date of birth',
      emailConsent: 'Receive news & offers by email',
      smsConsent: 'Receive news & offers by SMS/Viber',
      preferencesDesc: "Choose the categories you love: YAMATO will show you more of what you're into.",
      privacyNote: 'You can update or withdraw your marketing preferences at any time.',
      street: 'Street address',
      city: 'City',
      postalCode: 'Postal code',
      country: 'Country',
      company: 'Company (optional)',
    },
  },

  el: {
    lang: 'ΕΛ',
    nav: {
      home: 'Αρχική', experience: 'Η Εμπειρία', gaming: 'YA Gaming',
      social: 'YA Social', collectibles: 'Collectibles / TCG', tcg: 'TCG Lounge',
      bundles: 'Πακέτα & Πάσα', howto: 'Πώς Παίζεται', stores: 'Καταστήματα',
      events: 'Εκδηλώσεις', club: 'YAMATO Club', contact: 'Επικοινωνία', shop: 'Shop',
      prizes: 'Prizes',
    },
    hero: {
      badge: 'Ανοιχτά στην Αθήνα & Νέα Ερυθραία',
      h1a: 'Η Πραγματικότητα', h1b: 'Γίνεται', h1c: 'Παιχνίδι.',
      sub: 'Ο πρώτος premium αστικός προορισμός παιχνιδιού στην Ελλάδα. 100+ games, VR, TCG, social gaming και collectibles.',
      tagline: 'Μπες στο παιχνίδι.',
      cta1: 'Δες την Εμπειρία', cta2: 'Βρες Κατάστημα',
    },
    stats: { machines: 'Μηχανήματα', zones: 'Ζώνες', locations: 'Τοποθεσίες', fun: 'Ώρες Διασκέδασης' },
    footer: {
      desc: 'Ούτε κατάστημα. Ούτε game room. Πρώτο στην Ελλάδα. Φτιαγμένο για να επανακαθορίσει την αστική διασκέδαση.',
      nav: 'Πλοήγηση', more: 'Περισσότερα', rights: '© 2026 YAMATO Urban Play. Με επιφύλαξη παντός δικαιώματος.',
      legal: 'Πολιτική Απορρήτου · Όροι Χρήσης · GDPR',
    },
    cta: { findStore: 'Βρες Κατάστημα', joinClub: 'Γίνε Μέλος', viewAll: 'Όλα', browseAll: 'Αναζήτηση' },
    home: {
      featuredGames: { sub: 'Step Inside', title: 'The Lineup.', mobileCta: 'Όλα τα Games' },
      categories: { sub: 'Εξερεύνηση', title: 'Κατηγορίες Games' },
      prizeDrops: {
        sub: 'Τρέχουσα Λίστα',
        cta: 'Όλα τα Drops',
        locationNote: 'Η λίστα prizes ενδέχεται να διαφέρει ανά τοποθεσία',
        dropBadge: 'Drop',
        scrollHint: 'σύρε για εξερεύνηση',
      },
      prizeTeaser: {
        sub: 'Κέρδισε Κάτι Πραγματικό.',
        title: 'Prize games',
        titleAccent: 'που αξίζουν τον αγώνα.',
        desc: 'Claw machines, μάχες φιγούρων, προκλήσεις δεξιοτεχνίας — γεμάτα με anime heroes, gaming icons και pop-culture collectibles. Κάθε παιχνίδι είναι ευκαιρία για κάτι αληθινό.',
        cta1: 'Εξερεύνησε τα Prize Games',
        cta2: 'Δες τα Prize Drops',
        steps: [
          { n: '01', title: 'Διάλεξε',    desc: 'Επίλεξε το μηχάνημά σου και την πρόκλησή σου.' },
          { n: '02', title: 'Στόχευσε',   desc: 'Η δεξιοτεχνία και ο χρόνος αποφασίζουν.' },
          { n: '03', title: 'Κέρδισε',    desc: 'Πάρε το collectible σου.' },
          { n: '04', title: 'Παρουσίασε', desc: 'Η συλλογή σου μόλις σοβαρεύτηκε.' },
        ],
      },
      pillars: {
        sub: 'Μία επαναφορτιζόμενη κάρτα.',
        title: 'Η YAMATO Εμπειρία.',
        items: [
          { title: 'YA Gaming',      desc: '100+ premium arcade μηχανήματα σε 10 κατηγορίες — από VR μέχρι κλασικό pinball.' },
          { title: 'YA Social',      desc: 'AR darts, The Arena, shuffleboard — εμπειρίες φτιαγμένες για ομάδες και κοινές στιγμές.' },
          { title: 'YA Collectibles',desc: 'TCG κάρτες, limited merch, vinyl φιγούρες και αποκλειστικά YAMATO drops.' },
          { title: 'TCG Lounge',     desc: 'Pokémon, Yu-Gi-Oh!, One Piece τουρνουά και ένας αφιερωμένος χώρος κοινότητας.' },
        ],
      },
      events: { sub: 'Τι Γίνεται', title: 'Επερχόμενες Εκδηλώσεις', cta: 'Όλες οι Εκδηλώσεις' },
      bundles: {
        sub: 'Μία Κάρτα.',
        title: 'Η YAMATO Εμπειρία.',
        desc: 'Φόρτωσε και παίξε — χωρίς τέλος εισόδου, χωρίς όρια. Η YAMATO Playcard ξεκλειδώνει τα πάντα.',
        cta: 'Δες τα Πάσα',
      },
      faq: { sub: 'Ερωτήσεις', title: 'FAQ', cta: 'Πώς Παίζεται + Πλήρες FAQ' },
      club: {
        sub: 'Αποκλειστικό',
        title: 'Γίνε μέλος του YAMATO Club',
        desc: 'Πρώτη πρόσβαση. Αποκλειστικά drops. Εκδηλώσεις μελών. Για όσους περιμένουν κάτι παραπάνω από τη συνηθισμένη διασκέδαση — και επιστρέφουν.',
        cta: 'Προ-Εγγραφή Τώρα',
      },
    },
    ui: {
      perPage: 'Ανά σελίδα:',
      pageOf: 'σελίδα',
      of: 'από',
      loading: 'Φόρτωση…',
      loadingPrizes: 'Φόρτωση Prize Drops…',
      errorPrizes: 'Δεν ήταν δυνατή η φόρτωση.',
      explorePrizes: 'Εξερεύνησε τα Prize Games',
      prize: 'prize',
      prizes: 'prizes',
      products: 'προϊόντα',
      scrollHint: 'σύρε για εξερεύνηση',
      prevPage: '← Προηγ.',
      nextPage: 'Επόμ. →',
      howToWin: 'Πώς να Κερδίσεις',
      winSteps: [
        { n: '01', title: 'Διάλεξε παιχνίδι',     desc: 'Επίλεξε claw machine, figure game ή skill challenge.' },
        { n: '02', title: 'Στόχευσε',               desc: 'Δοκίμασε τη δεξιοτεχνία σου, βελτίωσε την τεχνική σου.' },
        { n: '03', title: 'Κέρδισε το prize σου',  desc: 'Πάρε σπίτι ένα pop-culture collectible που πραγματικά θέλεις.' },
        { n: '04', title: 'Παρουσίασε & Μοιράσου', desc: 'Δείξτο. Η συλλογή σου μόλις σοβαρεύτηκε.' },
      ],
      filters: 'Φίλτρα',
      search: 'Αναζήτηση…',
      all: 'Όλα',
      categories: 'Κατηγορίες',
      clearFilters: 'Καθαρισμός Φίλτρων',
      noProducts: 'Δεν βρέθηκαν προϊόντα',
      loadingProducts: 'Φόρτωση...',
    },
    pages: {
      experience: {
        hero: { sub: 'Η Εμπειρία', title: 'Η Πραγματικότητα Γίνεται Παιχνίδι.', desc: 'Το YAMATO δεν είναι απλά arcade. Είναι ένας κινηματογραφικός, καθηλωτικός αστικός προορισμός παιχνιδιού για κάθε τύπο παίκτη.' },
        philosophy: { label: 'Η Φιλοσοφία μας', title: 'Premium. Κινηματογραφικό. Δικό σου.', p1: 'Το YAMATO γεννήθηκε από μια ιδέα: ότι το παιχνίδι αξίζει να είναι premium. Μαζέψαμε τις καλύτερες arcade εμπειρίες — VR, simulators, social AR, pinball, TCG — και τις φέραμε σε έναν σκοτεινό, καθηλωτικό χώρο.', p2: 'Η αισθητική είναι ιαπωνικής έμπνευσης, αστική και ακατέργαστη. Η εμπειρία είναι κινηματογραφική. Η κοινότητα είναι τα πάντα.', ctaBrowse: 'Δες τα Games', ctaFind: 'Βρες μας' },
        stats: [{ n:'100+', l:'Premium Μηχανήματα' }, { n:'10', l:'Κατηγορίες' }, { n:'VR', l:'Πλήρης Εμβύθιση' }, { n:'TCG', l:'Card Gaming Lounge' }],
        zones: { label: 'Οι Ζώνες', title: 'Κατηγορίες Games' },
        diff: { label: 'Γιατί YAMATO', title: 'Τι μας Ξεχωρίζει' },
        diffItems: [
          { title: 'Επιλεγμένο, Όχι Τυχαίο', desc: 'Κάθε μηχάνημα στο YAMATO επιλέχθηκε χειροκίνητα για ποιότητα, παιξιμότητα και θέαμα. Χωρίς γέμισμα.' },
          { title: 'Premium Ατμόσφαιρα', desc: 'Σκοτεινό, κινηματογραφικό, ιαπωνικής έμπνευσης. Ένας χώρος που αισθάνεσαι τόσο καλά όσο τα games που τον γεμίζουν.' },
          { title: 'Κοινότητα Πρώτα', desc: 'Τουρνουά TCG, πρωταθλήματα VR, retro βραδιές. Το YAMATO είναι προορισμός, όχι απλά χώρος.' },
        ],
      },
      gaming: {
        hero: { sub: 'YA Gaming', title: 'Το Game Floor', desc: '100+ premium arcade μηχανήματα σε 10 κατηγορίες. Από πρωτοποριακό VR μέχρι διαχρονικά κλασικά.' },
        search: 'Αναζήτηση games…', all: 'Όλα', noResults: 'Δεν βρέθηκαν games.',
      },
      social: {
        hero: { sub: 'YA Social', title: 'Παίξτε Μαζί.', desc: 'Augmented reality, ομαδικές αρένες, darts, shuffleboard — εμπειρίες σχεδιασμένες για κοινές στιγμές και αξέχαστες βραδιές.' },
        section: { label: 'Social Gaming', title: 'Φέρτε όλη την Παρέα!', p1: 'Η ζώνη Social Entertainment & AR του YAMATO είναι εκεί που γίνεται η μαγεία για ομάδες. Ανταγωνιστείτε φίλους στην Arena, προκαλέστε ο ένας τον άλλον στο AR Darts ή μαζευτείτε γύρω από το shuffleboard.', p2: 'Ιδανικό για γενέθλια, εταιρικές εκδηλώσεις, βραδιές εξόδου ή απλά για να κάνετε παρέα.' },
        gamesLabel: 'Social Entertainment & AR', gamesTitle: 'Όλες οι Κοινωνικές Εμπειρίες',
      },
      collectibles: {
        hero: { sub: 'YA Collectibles', title: 'Μάζεψε. Ανταλλάξτε. Απόκτησε.', desc: 'TCG κάρτες, limited-edition merch, αποκλειστικές συνεργασίες και designer vinyl. Το YAMATO store.' },
        inStore: 'Διαθέσιμο στο κατάστημα', registerInterest: 'Εκδήλωση Ενδιαφέροντος',
        tcgSection: { label: 'TCG Lounge', title: 'Παίξε, Ανταλλάξτε & Διαγωνίσου', desc: 'Αποκλειστικός χώρος TCG με τακτικά τουρνουά και κοινοτικές εκδηλώσεις.', cta: 'Ανακάλυψε το TCG Lounge' },
      },
      tcg: {
        hero: { sub: 'TCG Lounge', title: 'Η Γωνιά των Card Games.', desc: 'Ένας αποκλειστικός χώρος για παίκτες Trading Card Games. Παίξε, ανταλλάξτε, μάζεψε, ανταγωνίσου. Pokémon, Yu-Gi-Oh!, One Piece και άλλα.' },
        games: [
          { name: 'Pokémon TCG', desc: 'Booster boxes, singles και ανταγωνιστικό παιχνίδι. Τακτικές επεκτάσεις σε απόθεμα.' },
          { name: 'Yu-Gi-Oh!', desc: 'Collector tins, booster packs και tournament-legal decks.' },
          { name: 'One Piece TCG', desc: 'Starter decks και boosters από το πιο γρήγορα αναπτυσσόμενο TCG στην αγορά.' },
        ],
        products: { label: 'Σε Απόθεμα', title: 'TCG Προϊόντα' },
        inStore: 'Διαθέσιμο στο κατάστημα',
        tournaments: { label: 'Ανταγωνίσου', title: 'Τουρνουά & Εκδηλώσεις', desc: 'Διοργανώνουμε τακτικά τουρνουά TCG για όλα τα επίπεδα. Βραβεία, δόξα και κοινότητα. Δες τις επερχόμενες ημερομηνίες.', cta1: 'Δες Εκδηλώσεις', cta2: 'Εκδήλωση Ενδιαφέροντος' },
        stats: [['Εβδομαδιαία','Τοπικά τουρνουά'],['Όλα τα Επίπεδα','Αρχάριος έως Pro'],['Βραβεία','Κέρδισε αποκλειστικές κάρτες'],['Κοινότητα','Ανάπτυξε τις δεξιότητές σου']],
      },
      bundles: {
        hero: { sub: 'Πακέτα & Πάσα', title: 'Παίξε Όπως Θέλεις.', desc: 'YAMATO Playcard, Summer Pass, Whole Gang Pass και Gift Cards. Διαθέσιμα σε όλες τις τοποθεσίες.' },
        custom: { title: 'Χρειάζεσαι κάτι συγκεκριμένο;', desc: 'Ομαδικές κρατήσεις, εταιρικές εκδηλώσεις, πακέτα γενεθλίων — θα το προσαρμόσουμε για σένα.', cta: 'Επικοινωνία' },
      },
      howto: {
        hero: { sub: 'Πώς Παίζεται', title: 'Μπες στο Παιχνίδι.', desc: 'Όλα όσα πρέπει να ξέρεις για να ξεκινήσεις το ταξίδι σου στο YAMATO.' },
        steps: { label: 'Βήμα Βήμα', title: 'Είναι Απλό' },
        stepItems: [
          { n:'01', title:'Επισκέψου ένα YAMATO', desc:'Μπες σε οποιοδήποτε κατάστημα YAMATO — Κέντρο Αθήνας ή Νέα Ερυθραία. Δεν απαιτείται κράτηση για ατομικό παιχνίδι.' },
          { n:'02', title:'Πάρε την Playcard σου', desc:'Παραλαβή YAMATO Playcard από την υποδοχή. Φόρτωσέ τη με credits — από €5.' },
          { n:'03', title:'Εξερεύνησε τον Χώρο', desc:'Πάνω από 100 μηχανήματα σε 10 κατηγορίες. Άγγιξε την Playcard σου σε οποιοδήποτε μηχάνημα για να αρχίσεις.' },
          { n:'04', title:'Νίκα, Ανέβα Επίπεδο, Επανάλαβε', desc:'Μάζεψε tickets από redemption games, προκάλεσε φίλους, ανακάλυψε νέες εμπειρίες. Η διασκέδαση δεν σταματά.' },
        ],
        playcard: { label: 'Το Κλειδί σου για το YAMATO', title: 'Η YAMATO Playcard', p1: 'Επαναφορτιζόμενη, παρακολουθήσιμη και λειτουργεί σε κάθε μηχάνημα σε κάθε τοποθεσία. Φόρτωσε από €5 ή στοιβάξτε για πλήρη session.', p2: 'Διαθέσιμη στην υποδοχή όλων των YAMATO.', cta: 'Δες τα Πάσα' },
        faq: { label: 'FAQ', title: 'Συχνές Ερωτήσεις' },
      },
      stores: {
        hero: { sub: 'Τοποθεσίες', title: 'Βρες το YAMATO σου.', desc: 'Δύο τοποθεσίες ανοιχτές στην Αττική. Σύντομα περισσότερες σε όλη την Ελλάδα.' },
        active: { label: 'Ανοιχτά Τώρα', title: 'Ενεργές Τοποθεσίες' },
        mapExplore: 'Εξερεύνηση στο Google Maps',
        coming: { label: 'Επέκταση', title: 'Σύντομα' },
        openInMaps: 'Άνοιγμα στο Maps',
      },
      events: {
        hero: { sub: 'Εκδηλώσεις & Social Hub', title: 'Τι Γίνεται.', desc: 'Τουρνουά, retro βραδιές, οικογενειακές ημέρες, πρωταθλήματα. Το ημερολόγιο εκδηλώσεων YAMATO.' },
        featured: { label: 'Προτεινόμενα', title: 'Μην το Χάσεις' },
        upcoming: { label: 'Επερχόμενα', title: 'Όλες οι Εκδηλώσεις' },
        social: { label: 'Social', title: 'Ακολούθησε τη Δράση', desc: 'Μείνε ενήμερος για όλες τις εκδηλώσεις, drops και highlights της κοινότητας.' },
      },
      club: {
        hero: { sub: 'YAMATO Club', title: 'Μπες στον Εσωτερικό Κύκλο.', desc: 'Προ-εγγραφή για το YAMATO Club. Αποκλειστικά οφέλη, πρώτη πρόσβαση, member drops και πολλά άλλα. Λανσάρισμα με την πρώτη μας τοποθεσία.' },
        benefits: { label: 'Οφέλη Μελών', title: 'Τι Κερδίζεις' },
        benefitItems: [
          { title: 'Πρώτη Πρόσβαση', desc: 'Πρώτος σε νέα games, drops και αποκλειστικές εκδηλώσεις πριν το κοινό.' },
          { title: 'Member Drops', desc: 'Αποκλειστικό YAMATO merchandise και limited-edition collectibles, μόνο για μέλη.' },
          { title: 'Priority Events', desc: 'Εγγυημένες θέσεις σε τουρνουά TCG, πρωταθλήματα VR και member-only βραδιές.' },
          { title: 'Member Perks', desc: 'Μπόνους γενεθλίων, loyalty credits και ειδικές τιμές σε passes.' },
          { title: 'Κοινότητα', desc: 'Γίνε μέλος μιας ιδιωτικής κοινότητας YAMATO παικτών, collectors και λάτρεων.' },
          { title: 'The Briefing', desc: 'Μηνιαίο newsletter YAMATO: νέα games, εκδηλώσεις, drops και παρασκήνιο.' },
        ],
        form: { label: 'Προ-Εγγραφή', title: 'Κράτα τη Θέση σου', sub: 'Δωρεάν εγγραφή. Δεν απαιτείται κάρτα. GDPR compliant.' },
      },
      contact: {
        hero: { sub: 'Επικοινωνία', title: 'Επικοινώνησε μαζί μας.', desc: 'Ερωτήσεις, ομαδικές κρατήσεις, press inquiries ή απλά θέλεις να πεις γεια.' },
        form: { label: 'Στείλε Μήνυμα', title: 'Φόρμα Επικοινωνίας' },
        locations: { label: 'Βρες μας', title: 'Τοποθεσίες' },
        openInMaps: 'Άνοιγμα στο Maps',
        socialTitle: 'Social Media',
      },
      prizes: {
        hero: {
          title: 'Τρέχοντα Prize Drops.',
          desc: 'Anime ήρωες, gaming icons, χαριτωμένοι χαρακτήρες και collectible φιγούρες που μπορείς να κερδίσεις στο YAMATO. Χωρίς καλάθι. Χωρίς online checkout. Μόνο prizes που αξίζουν τον αγώνα.',
          note: 'Διαθέσιμα σε επιλεγμένα prize games YAMATO. Η λίστα prizes ενδέχεται να διαφέρει.',
          cta1: 'Εξερεύνησε τα Prizes',
          cta2: 'Πώς Λειτουργούν τα Prize Games',
        },
        featured: { label: '★ Επιλεγμένα Drops', title: 'Επιλεγμένα Αυτή την Περίοδο' },
        filters: { all: 'Όλα τα Prizes', hero: 'Ανά Ήρωα', brand: 'Ανά Brand' },
        noResults: 'Δεν βρέθηκαν prizes.',
        gameTypeLabel: 'Κέρδισέ το στα',
        playToWin: 'Παίξε για να Κερδίσεις',
        seeHowToWin: 'Δες Πώς να Κερδίσεις',
        availableIn: 'Διαθέσιμο σε επιλεγμένα prize games',
        cta: {
          title: 'Πώς τα κερδίζεις;',
          desc: 'Διάλεξε ένα prize game του YAMATO, δοκίμασε τη δεξιοτεχνία σου και πάρε τον αγαπημένο σου pop-culture ήρωα σπίτι.',
          btn: 'Εξερεύνησε τα Prize Games',
        },
        homeTeaserTitle: 'Κέρδισε τους χαρακτήρες που πραγματικά θέλεις.',
        homeTeaserDesc: 'Anime ήρωες, gaming icons, χαριτωμένοι χαρακτήρες και collectible φιγούρες που σε περιμένουν στα prize games του YAMATO.',
        homeTeaserCta: 'Δες τα Prize Drops',
        prizeGamesTitle: 'Prize games που αξίζει να παίξεις.',
        prizeGamesDesc: 'Μηχανήματα δεξιοτεχνίας, συναρπαστικές προκλήσεις και premium pop-culture prizes που περιμένουν να τα κερδίσεις.',
        prizeGamesCta: 'Εξερεύνησε τα Prize Games',
      },
    },
    auth: {
      signIn: 'Σύνδεση',
      myYamato: 'My YAMATO',
      signInTitle: 'Σύνδεση στο YAMATO',
      signInDesc: 'Χωρίς κωδικό. Βάλε το email σου και θα σου στείλουμε σύνδεσμο ασφαλούς πρόσβασης.',
      emailLabel: 'Email',
      emailPlaceholder: 'το@email.σου',
      sendOTP: 'Αποστολή συνδέσμου',
      sendLink: 'Αποστολή Συνδέσμου',
      otpTitle: 'Έλεγξε το email σου',
      otpDesc: 'Στείλαμε 6ψήφιο κωδικό στο',
      otpLabel: 'Εισαγωγή 6ψήφιου κωδικού',
      otpPlaceholder: '000000',
      verifyOTP: 'Επαλήθευση κωδικού',
      backToEmail: 'Δοκίμασε άλλο email',
      sending: 'Αποστολή…',
      verifying: 'Επαλήθευση…',
      signOut: 'Αποσύνδεση',
      checkEmail: 'Έλεγξε το Email σου',
      linkSentDesc: 'Στείλαμε σύνδεσμο σύνδεσης στο {email}. Κάνε κλικ για να αποκτήσεις πρόσβαση στον λογαριασμό σου.',
      spamNote: 'Δεν το βρίσκεις; Έλεγξε το spam.',
      tryAgain: 'Δοκίμασε άλλο email',
      noAccount: 'Δεν είσαι μέλος;',
      joinCTA: 'Εγγραφή →',
    },
    join: {
      pageTitle: 'Γίνε μέλος του YAMATO Club',
      step1Title: 'Συμπλήρωσε το προφίλ σου',
      step1Desc: 'Χρησιμοποιούμε αυτές τις πληροφορίες για να εξατομικεύσουμε την εμπειρία σου στο Club.',
      step2Title: 'Τι σε ενδιαφέρει;',
      step2Desc: 'Επέλεξε τα αγαπημένα σου για να σου δείχνουμε περισσότερα από αυτά που αγαπάς.',
      step3Title: 'Μείνε ενήμερος',
      step3Desc: 'Επέλεξε πώς θέλεις να επικοινωνούμε μαζί σου. Μπορείς να αλλάξεις οποτεδήποτε.',
      welcomeTitle: 'Καλωσήρθες στο YAMATO Club',
      welcomeDesc: 'Είσαι μέσα. Prize drops, νέα μελών και YAMATO εμπειρίες είναι τώρα πιο κοντά από ποτέ.',
      exploreCTA: 'Εξερεύνησε τα Prize Drops',
      dashboardCTA: 'Πήγαινε στο My YAMATO',
      alreadyMember: 'Είσαι ήδη μέλος του YAMATO Club!',
      firstName: 'Όνομα',
      lastName: 'Επώνυμο',
      phone: 'Κινητό τηλέφωνο',
      birthdate: 'Ημερομηνία γέννησης',
      agreeTerms: 'Αποδέχομαι τους Όρους του YAMATO Club και την Πολιτική Απορρήτου.',
      agreeEmail: 'Θέλω να λαμβάνω νέα YAMATO, προσφορές και ενημερώσεις Prize Drops μέσω email.',
      agreeSMS: 'Θέλω να λαμβάνω νέα YAMATO, προσφορές και ενημερώσεις Prize Drops μέσω SMS/Viber.',
      next: 'Συνέχεια',
      saving: 'Αποθήκευση…',
      termsRequired: 'Πρέπει να αποδεχτείς τους Όρους και την Πολιτική Απορρήτου για να γίνεις μέλος.',
      interests: ['Anime Ήρωες', 'Gaming Icons', 'Ταινίες & Σειρές', 'Cute & Kawaii', 'Collector Figures', 'Prize Drops', 'Ειδικές Προσφορές', 'Εκδηλώσεις'],
    },
    dashboard: {
      title: 'My YAMATO',
      profile: 'Το Προφίλ μου',
      club: 'YAMATO Club',
      preferences: 'Οι Προτιμήσεις μου',
      orders: 'Οι Παραγγελίες μου',
      addresses: 'Οι Διευθύνσεις μου',
      marketing: 'Προτιμήσεις Επικοινωνίας',
      signOut: 'Αποσύνδεση',
      memberSince: 'Μέλος από',
      memberStatus: 'Κατάσταση',
      memberNumber: 'Αρ. Μέλους',
      active: 'Ενεργό',
      pending: 'Εκκρεμεί',
      noOrders: 'Δεν υπάρχουν παραγγελίες ακόμα.',
      noAddresses: 'Δεν έχουν αποθηκευτεί διευθύνσεις ακόμα.',
      save: 'Αποθήκευση αλλαγών',
      saving: 'Αποθήκευση…',
      saved: 'Αποθηκεύτηκε!',
      addAddress: 'Νέα διεύθυνση',
      defaultAddress: 'Προεπιλογή',
      setDefault: 'Ορισμός ως προεπιλογή',
      deleteAddress: 'Διαγραφή',
      shipping: 'Αποστολή',
      billing: 'Τιμολόγηση',
      notMember: 'Δεν έχεις γίνει ακόμα μέλος του YAMATO Club.',
      joinNow: 'Γίνε μέλος του YAMATO Club',
      firstName: 'Όνομα',
      lastName: 'Επώνυμο',
      email: 'Email',
      phone: 'Κινητό',
      birthdate: 'Ημερομηνία γέννησης',
      emailConsent: 'Λήψη νέων & προσφορών μέσω email',
      smsConsent: 'Λήψη νέων & προσφορών μέσω SMS/Viber',
      preferencesDesc: 'Επέλεξε τις κατηγορίες που αγαπάς: το YAMATO θα σου δείχνει περισσότερα από αυτά που σε ενδιαφέρουν.',
      privacyNote: 'Μπορείς να ενημερώσεις ή να αποσύρεις τις προτιμήσεις σου για επικοινωνία οποτεδήποτε.',
      street: 'Οδός και αριθμός',
      city: 'Πόλη',
      postalCode: 'Ταχυδρομικός κώδικας',
      country: 'Χώρα',
      company: 'Εταιρεία (προαιρετικό)',
    },
  },

  ja: {
    lang: 'JP',
    nav: {
      home: 'ホーム', experience: '体験', gaming: 'YAゲーミング',
      social: 'YAソーシャル', collectibles: 'YAコレクタブル', tcg: 'TCGラウンジ',
      bundles: 'バンドル＆パス', howto: '遊び方', stores: '店舗',
      events: 'イベント', club: 'YAMATOクラブ', contact: 'お問い合わせ', shop: 'ショップ',
      prizes: 'プライズ',
    },
    hero: {
      badge: 'アテネ＆ネア・エリスレアにオープン',
      h1a: '現実が', h1b: 'ゲームに', h1c: 'なる場所。',
      sub: 'ギリシャ初のプレミアム・アーバン・プレイ施設。100以上のゲーム、VR、TCG、ソーシャルゲーミングとコレクタブル。',
      tagline: 'ゲームに入れ。',
      cta1: '体験を探索する', cta2: '店舗を探す',
    },
    stats: { machines: 'アーケード機', zones: 'ゲームゾーン', locations: '店舗数', fun: '楽しさ∞' },
    footer: {
      desc: '現実がゲームになる場所。ギリシャ初のプレミアム・アーバン・プレイ施設。',
      nav: 'ナビゲーション', more: 'その他', rights: '© 2026 YAMATO Urban Play. 無断転載禁止。',
      legal: 'プライバシーポリシー · 利用規約 · GDPR',
    },
    cta: { findStore: '店舗を探す', joinClub: 'クラブに参加', viewAll: '全て見る', browseAll: '検索' },
    home: {
      featuredGames: { sub: 'ハイライト', title: 'フィーチャードゲーム', mobileCta: '全ゲームを見る' },
      categories: { sub: '探索', title: 'ゲームカテゴリー' },
      prizeDrops: {
        sub: '現在のラインナップ',
        cta: '全ドロップを見る',
        locationNote: 'プライズラインナップは店舗により異なる場合があります',
        dropBadge: 'ドロップ',
        scrollHint: 'スクロールして探索',
      },
      prizeTeaser: {
        sub: '買わずに勝ち取れ',
        title: 'Prize games',
        titleAccent: '勝つ価値のある。',
        desc: 'クローマシン、フィギュアバトル、スキルチャレンジ — アニメヒーロー、ゲームアイコン、ポップカルチャーコレクタブルが詰まっています。',
        cta1: 'プライズゲームを探索',
        cta2: 'プライズドロップを見る',
        steps: [
          { n: '01', title: '選ぶ', desc: 'マシンとチャレンジを選択。' },
          { n: '02', title: '狙う', desc: 'スキルとタイミングが勝敗を決める。' },
          { n: '03', title: '勝つ', desc: 'コレクタブルをゲット。' },
          { n: '04', title: '飾る', desc: 'あなたの棚がレベルアップ。' },
        ],
      },
      pillars: {
        sub: '提供するもの',
        title: 'YAMATO体験',
        items: [
          { title: 'YAゲーミング',    desc: '10カテゴリーの100以上のプレミアムアーケード機 — VRからクラシックピンボールまで。' },
          { title: 'YAソーシャル',    desc: 'ARダーツ、アリーナ、シャッフルボード — グループと共有の瞬間のための体験。' },
          { title: 'YAコレクタブル',  desc: 'TCGカード、限定グッズ、ビニールフィギュア、限定YAMATOドロップ。' },
          { title: 'TCGラウンジ',     desc: 'ポケモン、遊戯王、ワンピースのトーナメントとコミュニティスペース。' },
        ],
      },
      events: { sub: '開催中', title: '近日イベント', cta: '全イベント' },
      bundles: {
        sub: 'もっと遊ぼう、節約しよう',
        title: 'バンドル＆パス',
        desc: 'YAMATOプレイカード、サマーパス、ホールギャングパス、ギフトカード。',
        cta: 'パスを見る',
      },
      faq: { sub: '質問', title: 'よくある質問', cta: '遊び方＋完全FAQ' },
      club: {
        sub: '限定',
        title: 'YAMATOクラブに参加',
        desc: '早期アクセス、限定ドロップ、メンバーイベント。今すぐ事前登録。',
        cta: '今すぐ事前登録',
      },
    },
    ui: {
      perPage: '表示件数:',
      pageOf: 'ページ',
      of: '/',
      loading: '読み込み中…',
      loadingPrizes: 'プライズドロップを読み込み中…',
      errorPrizes: '読み込めませんでした。',
      explorePrizes: 'プライズゲームを探す',
      prize: 'プライズ',
      prizes: 'プライズ',
      products: '商品',
      scrollHint: 'スクロールして探索',
      prevPage: '← 前へ',
      nextPage: '次へ →',
      howToWin: '獲得方法',
      winSteps: [
        { n: '01', title: 'ゲームを選ぶ',    desc: 'クローマシン、フィギュアゲーム、スキルチャレンジを選択。' },
        { n: '02', title: '狙って打つ',       desc: 'スキルを試し、テクニックを磨く。' },
        { n: '03', title: 'プライズをゲット', desc: 'お気に入りのキャラクターを持ち帰ろう。' },
        { n: '04', title: '飾って共有',       desc: '見せびらかそう。棚がレベルアップ。' },
      ],
      filters: 'フィルター',
      search: '検索…',
      all: '全て',
      categories: 'カテゴリー',
      clearFilters: 'フィルターをクリア',
      noProducts: '商品が見つかりません',
      loadingProducts: '読み込み中...',
    },
    pages: {
      experience: {
        hero: { sub: '体験', title: '現実がゲームになる場所。', desc: 'YAMATOはただのアーケードではありません。あらゆるプレイヤーのためにデザインされた没入型のアーバン・プレイ施設です。' },
        philosophy: { label: '私たちの哲学', title: 'プレミアム。映画的。あなたのもの。', p1: 'YAMATOはひとつのアイデアから生まれました：ゲームはプレミアムであるべきという信念。VR、モーションシミュレーター、ソーシャルAR、クラシックピンボール、TCGを一つの没入型空間に集めました。', p2: 'その美学は日本的で、アーバンで、ローな質感。体験は映画的。コミュニティはすべて。', ctaBrowse: 'ゲームを見る', ctaFind: '場所を探す' },
        stats: [{ n:'100+', l:'プレミアム機' }, { n:'10', l:'ゲームカテゴリー' }, { n:'VR', l:'完全没入' }, { n:'TCG', l:'カードゲームラウンジ' }],
        zones: { label: 'ゾーン', title: 'ゲームカテゴリー' },
        diff: { label: 'YAMATOを選ぶ理由', title: '他と違う点' },
        diffItems: [
          { title: '厳選されたラインナップ', desc: 'YAMATOのすべての機械は品質とプレイアビリティのために手作業で選ばれました。' },
          { title: 'プレミアムな雰囲気', desc: 'ダーク、映画的、日本的。ゲームと同様に心地よいスペース。' },
          { title: 'コミュニティ第一', desc: 'TCGトーナメント、VRチャンピオンシップ、レトロナイト。YAMATOは目的地です。' },
        ],
      },
      gaming: {
        hero: { sub: 'YAゲーミング', title: 'ゲームフロア', desc: '10カテゴリーの100以上のプレミアムアーケード機。' },
        search: 'ゲームを検索…', all: '全て', noResults: 'ゲームが見つかりません。',
      },
      social: {
        hero: { sub: 'YAソーシャル', title: '一緒に遊ぼう。', desc: '拡張現実、グループアリーナ、ダーツ、シャッフルボード — 共有の瞬間のための体験。' },
        section: { label: 'ソーシャルゲーミング', title: '仲間全員を連れてきて！', p1: 'YAMATOのソーシャル&ARゾーンはグループにとって魔法が起こる場所。', p2: '誕生日、コーポレートイベント、外出の夜に最適。' },
        gamesLabel: 'ソーシャルエンターテインメント&AR', gamesTitle: 'すべてのソーシャル体験',
      },
      collectibles: {
        hero: { sub: 'YAコレクタブル', title: '集める。交換する。所有する。', desc: 'TCGカード、限定版グッズ、デザイナービニール。YAMATOストア。' },
        inStore: '店舗でご購入いただけます', registerInterest: '興味を登録',
        tcgSection: { label: 'TCGラウンジ', title: '遊ぶ、交換する、競う', desc: '定期的なトーナメントとコミュニティイベント。', cta: 'TCGラウンジを発見' },
      },
      tcg: {
        hero: { sub: 'TCGラウンジ', title: 'カードゲームの場所。', desc: 'トレーディングカードゲームプレイヤーのための専用スペース。ポケモン、遊戯王、ワンピースなど。' },
        games: [
          { name: 'ポケモンTCG', desc: 'ブースターボックス、シングル、競技プレイ。' },
          { name: '遊戯王！', desc: 'コレクター缶、ブースターパック、トーナメント対応デッキ。' },
          { name: 'ワンピースTCG', desc: 'スターターデッキとブースター。' },
        ],
        products: { label: '在庫あり', title: 'TCG製品' },
        inStore: '店舗でご購入いただけます',
        tournaments: { label: '競争', title: 'トーナメント＆イベント', desc: 'すべてのレベルの定期TCGトーナメント。', cta1: 'イベントを見る', cta2: '興味を登録' },
        stats: [['毎週','地域トーナメント'],['全レベル','初心者からプロまで'],['賞品','限定カードを獲得'],['コミュニティ','スキルを向上']],
      },
      bundles: {
        hero: { sub: 'バンドル＆パス', title: '自分流に遊ぼう。', desc: 'YAMATOプレイカード、サマーパス、ホールギャングパス、ギフトカード。' },
        custom: { title: '特定のものが必要ですか？', desc: 'グループ予約、コーポレートイベント、誕生日パッケージ。', cta: 'お問い合わせ' },
      },
      howto: {
        hero: { sub: '遊び方', title: 'ゲームに入れ。', desc: 'YAMATOの旅を始めるために知っておくべきすべて。' },
        steps: { label: 'ステップごとに', title: '簡単です' },
        stepItems: [
          { n:'01', title:'YAMATO店舗を訪問', desc:'アテネセンターまたはネア・エリスレアのYAMATO店舗へ。予約不要。' },
          { n:'02', title:'プレイカードを取得', desc:'フロントデスクでYAMATOプレイカードを受け取ります。€5からロード。' },
          { n:'03', title:'フロアを探索', desc:'プレイカードを任意の機械にタップして開始。' },
          { n:'04', title:'勝って、レベルアップ、繰り返す', desc:'チケットを集め、友達に挑戦し、新しい体験を発見。' },
        ],
        playcard: { label: 'YAMATOへの鍵', title: 'YAMATOプレイカード', p1: '再チャージ可能、すべての機械で使用可能。', p2: 'すべてのYAMATO店舗で利用可能。', cta: 'パスを見る' },
        faq: { label: 'よくある質問', title: 'よくある質問' },
      },
      stores: {
        hero: { sub: '場所', title: 'あなたのYAMATOを見つけて。', desc: 'アッティカに2店舗。ギリシャ全土で展開予定。' },
        active: { label: '今すぐオープン', title: 'アクティブな店舗' },
        mapExplore: 'Googleマップで探索',
        coming: { label: '拡張', title: '近日公開' },
        openInMaps: 'マップで開く',
      },
      events: {
        hero: { sub: 'イベント＆ソーシャルハブ', title: '開催中のイベント。', desc: 'トーナメント、レトロナイト、ファミリーデー。' },
        featured: { label: '注目', title: 'お見逃しなく' },
        upcoming: { label: '近日開催', title: 'すべてのイベント' },
        social: { label: 'ソーシャル', title: 'アクションをフォロー', desc: 'すべてのイベント、ドロップをチェック。' },
      },
      club: {
        hero: { sub: 'YAMATOクラブ', title: 'インナーサークルに参加。', desc: 'YAMATOクラブへの事前登録。特別特典、早期アクセス、メンバードロップなど。' },
        benefits: { label: 'メンバー特典', title: '得られるもの' },
        benefitItems: [
          { title: '早期アクセス', desc: '新しいゲーム、ドロップ、限定イベントへの最初のアクセス。' },
          { title: 'メンバードロップ', desc: 'メンバー限定の限定グッズとコレクタブル。' },
          { title: 'プライオリティイベント', desc: 'TCGトーナメント、VRチャンピオンシップの保証席。' },
          { title: 'メンバー特典', desc: '誕生日ボーナス、ロイヤリティクレジット。' },
          { title: 'コミュニティ', desc: 'YAMATOプレイヤーのプライベートコミュニティ。' },
          { title: 'ブリーフィング', desc: '月刊YAMATOニュースレター。' },
        ],
        form: { label: '事前登録', title: 'スポットを確保', sub: '無料。カード不要。GDPR準拠。' },
      },
      contact: {
        hero: { sub: 'お問い合わせ', title: 'ご連絡ください。', desc: '質問、グループ予約、またはただご挨拶。' },
        form: { label: 'メッセージを送る', title: 'お問い合わせフォーム' },
        locations: { label: '場所を探す', title: '店舗' },
        openInMaps: 'マップで開く',
        socialTitle: 'ソーシャルメディア',
      },
      prizes: {
        hero: {
          title: '現在のプライズドロップ。',
          desc: 'YAMATOで勝てるアニメヒーロー、ゲームアイコン、かわいいキャラクター。',
          note: '選択されたYAMATOプライズゲームで利用可能。',
          cta1: 'プライズドロップを探索',
          cta2: 'プライズゲームの仕組み',
        },
        featured: { label: '★ 注目ドロップ', title: '今シーズンの厳選品' },
        filters: { all: '全プライズ', hero: 'ヒーロー別', brand: 'ブランド別' },
        noResults: 'プライズが見つかりません。',
        gameTypeLabel: 'ここで勝てます',
        playToWin: '勝つためにプレイ',
        seeHowToWin: '勝ち方を見る',
        availableIn: '選択されたプライズゲームで利用可能',
        cta: {
          title: 'どうやって勝つの？',
          desc: 'YAMATOプライズゲームを選び、スキルをテストして、お気に入りのヒーローを持ち帰りましょう。',
          btn: 'プライズゲームを探索',
        },
        homeTeaserTitle: '本当に欲しいキャラクターを勝ち取れ。',
        homeTeaserDesc: 'アニメヒーロー、ゲームアイコン、かわいいキャラクターがYAMATOのプライズゲームで待っています。',
        homeTeaserCta: 'プライズドロップを見る',
        prizeGamesTitle: 'プレイする価値のあるプライズゲーム。',
        prizeGamesDesc: 'スキルベースの機械とプレミアムポップカルチャープライズ。',
        prizeGamesCta: 'プライズゲームを探索',
      },
    },
    auth: {
      signIn: 'ログイン',
      myYamato: 'My YAMATO',
      signInTitle: 'YAMATOにログイン',
      signInDesc: 'パスワード不要。メールアドレスを入力してセキュアなリンクを受け取ります。',
      emailLabel: 'メールアドレス',
      emailPlaceholder: 'your@email.com',
      sendOTP: 'ログインリンクを送る',
      otpTitle: 'メールを確認してください',
      otpDesc: '6桁のコードを送信しました',
      otpLabel: '6桁のコードを入力',
      otpPlaceholder: '000000',
      verifyOTP: 'コードを確認',
      backToEmail: '別のメールアドレスを試す',
      sending: '送信中…',
      verifying: '確認中…',
      signOut: 'ログアウト',
    },
    join: {
      pageTitle: 'YAMATOクラブに参加',
      step1Title: 'プロフィールを完成させる',
      step1Desc: 'クラブ体験をパーソナライズするために使用します。',
      step2Title: '何に興味がありますか？',
      step2Desc: 'お気に入りを選んで、より多くを表示させましょう。',
      step3Title: '最新情報を受け取る',
      step3Desc: '連絡方法を選んでください。いつでも変更できます。',
      welcomeTitle: 'YAMATOクラブへようこそ',
      welcomeDesc: 'プライズドロップ、メンバーニュース、YAMATO体験がより身近になりました。',
      exploreCTA: 'プライズドロップを探索',
      dashboardCTA: 'My YAMATOへ',
      alreadyMember: 'すでにYAMATOクラブのメンバーです！',
      firstName: '名',
      lastName: '姓',
      phone: '携帯電話',
      birthdate: '生年月日',
      agreeTerms: 'YAMATOクラブ利用規約とプライバシーポリシーに同意します。',
      agreeEmail: 'YAMATOのニュース、特典、プライズドロップ情報をメールで受け取りたい。',
      agreeSMS: 'YAMATOのニュース、特典、プライズドロップ情報をSMSで受け取りたい。',
      next: '次へ',
      saving: '保存中…',
      termsRequired: '参加するには利用規約とプライバシーポリシーへの同意が必要です。',
      interests: ['アニメヒーロー', 'ゲームアイコン', '映画＆シリーズ', 'キュート＆カワイイ', 'コレクターフィギュア', 'プライズドロップ', 'スペシャルオファー', 'イベント'],
    },
    dashboard: {
      title: 'My YAMATO',
      profile: 'プロフィール',
      club: 'YAMATOクラブ',
      preferences: '好み設定',
      orders: '注文履歴',
      addresses: '住所',
      marketing: 'マーケティング設定',
      signOut: 'ログアウト',
      memberSince: 'メンバー登録日',
      memberStatus: 'メンバーシップ',
      memberNumber: 'メンバー番号',
      active: 'アクティブ',
      pending: '保留中',
      noOrders: 'まだ注文がありません。',
      noAddresses: 'まだ住所が保存されていません。',
      save: '変更を保存',
      saving: '保存中…',
      saved: '保存しました！',
      addAddress: '新しい住所を追加',
      defaultAddress: 'デフォルト',
      setDefault: 'デフォルトに設定',
      deleteAddress: '削除',
      shipping: '配送先',
      billing: '請求先',
      notMember: 'まだYAMATOクラブのメンバーではありません。',
      joinNow: 'YAMATOクラブに参加',
      firstName: '名',
      lastName: '姓',
      email: 'メール',
      phone: '携帯電話',
      birthdate: '生年月日',
      emailConsent: 'メールでニュース＆特典を受け取る',
      smsConsent: 'SMSでニュース＆特典を受け取る',
      preferencesDesc: 'お気に入りのカテゴリーを選んでください。',
      privacyNote: 'マーケティング設定はいつでも更新または取り消しできます。',
      street: '住所',
      city: '市区町村',
      postalCode: '郵便番号',
      country: '国',
      company: '会社（任意）',
    },
  },
}

const LanguageContext = createContext({})
const LANGUAGES = ['en', 'el', 'ja']

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en')
  return (
    <LanguageContext.Provider value={{ lang, t: translations[lang], setLang, languages: LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLang = () => useContext(LanguageContext)
